spring:
  datasource:
    url: jdbc:mysql://localhost:3306/synergy?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: synergy
    password: pw1234!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 1000

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.jdbc.core: DEBUG
app:
  jwt:
    secret: "this_is_a_demo_secret_for_local_dev_change_me_please_1234567890abcd"