spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://connectdb.cpgqkmy0sm0o.ap-northeast-2.rds.amazonaws.com:3306/connectserver
    username: root
    password: 12341234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # 첫 세팅은 update, 나중엔 validate 권장
    open-in-view: false

server:
  port: 8080

app:
  jwt:
    secret: "please-change-to-a-random-very-long-secret-at-least-32-bytes"
    expiry-seconds: 3600